# Generated by Django 4.2.5 on 2023-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_dustbindata_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('fill_level', models.IntegerField()),
                ('is_full', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='DustbinData',
        ),
    ]
