# Generated by Django 4.2.5 on 2023-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_dustbindata_delete_dustbin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustbinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DustbinData',
        ),
    ]
