# Generated by Django 4.2.5 on 2024-01-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_rename_fill_percentage_dustbindata_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbindata',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
