# Generated by Django 4.2.5 on 2024-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='additional_info',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
