# Generated by Django 4.2.5 on 2024-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_alter_registration_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
