# Generated by Django 4.2.5 on 2024-02-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
