# Generated by Django 4.2.5 on 2024-02-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
    ]
