# Generated by Django 4.2.5 on 2024-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_acceptedregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
