# Generated by Django 4.2.5 on 2023-11-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_dustbin_delete_dustbindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustbinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.FloatField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Dustbin',
        ),
    ]
