# Generated by Django 4.2.5 on 2023-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_distancemeasurement_delete_dustbinstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustbinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_percentage', models.FloatField()),
                ('is_filled', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DistanceMeasurement',
        ),
    ]
