# Generated by Django 4.2.5 on 2024-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_dustbindata_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbindata',
            name='kathmandu_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
