# Generated by Django 4.2.5 on 2024-01-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_dustbindata_kathmandu_time'),
    ]

    operations = [
    ]
