# Generated by Django 4.2.5 on 2024-01-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20240104_2059'),
    ]

    operations = [
    ]
