# Generated by Django 4.2.5 on 2024-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20240106_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbindata',
            name='location',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
