# Generated by Django 4.2.5 on 2024-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(null='True'),
            preserve_default='True',
        ),
    ]
